CREATE TABLE m_department (
    dept_code VARCHAR(10) NOT NULL PRIMARY KEY,
    state_code VARCHAR(10) NOT NULL,
    dept_name VARCHAR(255) NOT NULL,
    dept_name_ll VARCHAR(255) NOT NULL,
    FOREIGN KEY (state_code) REFERENCES m_state(state_code),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    insert_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    insert_ip VARCHAR(50) NOT NULL DEFAULT 'NA',
    insert_by VARCHAR(100) NOT NULL DEFAULT 'NA',
    updated_date TIMESTAMP DEFAULT NULL,
    update_ip VARCHAR(50) DEFAULT NULL,
    update_by VARCHAR(100) DEFAULT NULL
);

DROP TABLE m_department;


INSERT INTO m_department (dept_code,state_code,dept_name,dept_name_ll)
VALUES
('MH7','27','Agriculture Department','कृषी विभाग, महाराष्ट'),
('MH42','27','Animal Husbandry, Dairy Development and Fisheries Department, Maharashtra','पशुसंवर्धन, दुग्धविकास आणि मत्स्यव्यवसाय विभाग, महाराष्ट्'),
('MH14','27','Co-operation and Textiles Department, Maharashtra','सहकार व वस्त्रोद्योग विभाग'),
('MH10','27','Election Department, Maharashtra','निवडणूक विभाग, महाराष्ट्र'),
('MH15','27','Employment and Self Employment Department, Maharashtra','रोजगार व स्व-रोजगार विभाग, महाराष्ट्र'),
('MH16','27','Environment Department, Maharashtra','पर्यावरण विभाग, महाराष्ट्र'),
('MH1','27','Finance Department, Maharashtra','वित्त विभाग, महाराष्ट्र'),
('MH12','27','Food, Civil Supplies and Consumer Protection Department, Maharashtra','अन्न, नागरी पुरवठा व ग्राहक संरक्षण विभाग, महाराष्ट्र'),
('MH18','27','General Administration Department, Maharashtra','सामान्य प्रशासन विभाग, महाराष्ट्र'),
('MH19','27','Higher and Technical Education Department, Maharashtra','उच्च व तांत्रिक शिक्षण विभाग, महाराष्ट्र'),
('MH20','27','Home Department, Maharashtra','गृह विभाग, महाराष्ट्र'),
('MH22','27','Housing Department, Maharashtra','गृहनिर्माण विभाग, महाराष्ट्र'),
('MH23','27','Industries, Energy and Labour Department, Maharashtra','उद्योग, ऊर्जा व कामगार विभाग, महाराष्ट्र'),
('MH25','27','Information Technology Department, Maharashtra','माहिती तंत्रज्ञान विभाग, महाराष्ट्र'),
('MH13','27','Law and Judiciary Department, Maharashtra','कायदा व न्याय विभाग, महाराष्ट्र'),
('MH27','27','Medical Education and Drugs Department, Maharashtra','वैद्यकीय शिक्षण व औषध विभाग, महाराष्ट्र'),
('MH28','27','Minorities Development Department, Maharashtra','अल्पसंख्याक विकास विभाग, महाराष्ट्र'),
('MH45','27','Motor Vehicles Department (R.T.O.), Maharashtra','मोटार वाहन विभाग (आर.टी.ओ.), महाराष्ट्र'),
('MH29','27','Parliamentary Affairs Department, Maharashtra','संसदीय कार्य विभाग, महाराष्ट्र'),
('MH30','27','Planning Department, Maharashtra','योजना विभाग, महाराष्ट्र'),
('MH31','27','Public Health and Family Welfare Department, Maharashtra','सार्वजनिक आरोग्य व कुटुंब कल्याण विभाग, महाराष्ट्र'),
('MH32','27','Public Works Department, Maharashtra','सार्वजनिक बांधकाम विभाग, महाराष्ट्र'),
('MH43','27','Relief and Rehabilitation Department, Maharashtra','आपत्ती व्यवस्थापन व पुनर्वसन विभाग, महाराष्ट्र'),
('MH9','27','Revenue and Forest Department, Maharashtra','महसूल व वन विभाग, महाराष्ट्र'),
('MH6','27','Rural Development and Panchayat Raj Department, Maharashtra','ग्रामीण विकास व पंचायत राज विभाग, महाराष्ट्र'),
('MH46','27','Sales Tax Department, Maharashtra','विक्रीकर विभाग, महाराष्ट्र'),
('MH34','27','School Education and Sports Department, Maharashtra','शालेय शिक्षण व क्रीडा विभाग, महाराष्ट्र'),
('MH35','27','Social Justice and Special Assistance Department, Maharashtra','सामाजिक न्याय व विशेष सहाय्य विभाग, महाराष्ट्र'),
('MH37','27','Tourism and Cultural Affairs Department, Maharashtra','पर्यटन व सांस्कृतिक कार्य विभाग, महाराष्ट्र'),
('MH36','27','Tribal Development Department, Maharashtra','आदिवासी विकास विभाग, महाराष्ट्र'),
('MH38','27','Urban Development Department, Maharashtra','नगर विकास विभाग, महाराष्ट्र'),
('MH3','27','Water Conservation Department, Maharashtra','पाणी संवर्धन विभाग, महाराष्ट्र'),
('MH39','27','Water Resources Department, Maharashtra','पाणी संसाधन विभाग, महाराष्ट्र'),
('MH40','27','Water Supply and Sanitation Department, Maharashtra','पाणीपुरवठा व स्वच्छता विभाग, महाराष्ट्र'),
('MH41','27','Women and Child Development Department, Maharashtra','महिला व बाल विकास विभाग, महाराष्ट्र'),
('AN9','35','Agriculture Department, Andaman & Nicobar','कृषी विभाग, अंदमान आणि निकोबार'),
('AN55','35','Andaman & Nicobar Tourism','अंदमान आणि निकोबार पर्यटन'),
('AN23','35','Andaman Public Works Department (APWD), Andaman & Nicobar','अंदमान सार्वजनिक बांधकाम विभाग (APWD), अंदमान आणि निकोबार'),
('AN11','35','Animal Husbandry and Veterinary Services Department, Andaman & Nicobar','पशुपालन आणि पशुवैद्यकीय सेवा विभाग, अंदमान आणि निकोबार'),
('AN7','35','Civil Supplies and Consumer Affairs Department, Andaman & Nicobar','नागरी पुरवठा व ग्राहक व्यवहार विभाग, अंदमान आणि निकोबार'),
('AN42','35','Cooperative Department, Andaman & Nicobar','सहकारी विभाग, अंदमान आणि निकोबार'),
('AN51','35','Economics & Statistics Department, Andaman & Nicobar','अर्थशास्त्र आणि सांख्यिकी विभाग, अंदमान आणि निकोबार'),
('AN3','35','Education Department, Andaman & Nicobar','शिक्षण विभाग, अंदमान आणि निकोबार'),
('AN4','35','Election Department, Andaman & Nicobar','निवडणूक विभाग, अंदमान आणि निकोबार'),
('AN30','35','Electricity Department, Andaman & Nicobar','वीज विभाग, अंदमान आणि निकोबार'),
('AN20','35','Environment & Forest Department, Andaman & Nicobar','पर्यावरण आणि वन विभाग, अंदमान आणि निकोबार'),
('AN52','35','Finance Department, Andaman & Nicobar','वित्त विभाग, अंदमान आणि निकोबार'),
('AN8','35','Fisheries Department, Andaman & Nicobar','मत्स्य विभाग, अंदमान आणि निकोबार'),
('AN2','35','Health Department, Andaman & Nicobar','आरोग्य विभाग, अंदमान आणि निकोबार'),
('AN54','35','Home & Vigilance Department, Andaman & Nicobar','गृह आणि दक्षता विभाग, अंदमान आणि निकोबार'),
('AN17','35','Industries Department, Andaman & Nicobar','उद्योग विभाग, अंदमान आणि निकोबार'),
('AR17','12','Horticulture Department, Arunachal Pradesh','उद्यान विभाग, अरुणाचल प्रदेश'),
('AR54','12','Hydro Power Development Department, Arunachal Pradesh','जलविद्युत विकास विभाग, अरुणाचल प्रदेश'),
('AR18','12','Industries Department, Arunachal Pradesh','उद्योग विभाग, अरुणाचल प्रदेश'),
('AR62','12','Information Technology Department, Arunachal Pradesh','माहिती तंत्रज्ञान विभाग, अरुणाचल प्रदेश'),
('AR19','12','Information, Public Relations and Printing Department, Arunachal Pradesh','माहिती, जनसंपर्क आणि मुद्रण विभाग, अरुणाचल प्रदेश'),
('AR20','12','Irrigation and Flood Control (Water Resources) Department, Arunachal Pradesh','सिंचन आणि पूर नियंत्रण (जलसंपदा) विभाग, अरुणाचल प्रदेश'),
('AR21','12','Labour and Employment Department, Arunachal Pradesh','कामगार आणि रोजगार विभाग, अरुणाचल प्रदेश'),
('AR22','12','Land Management Department, Arunachal Pradesh','जमीन व्यवस्थापन विभाग, अरुणाचल प्रदेश'),
('AR23','12','Law & Judicial Department, Arunachal Pradesh','कायदा आणि न्याय विभाग, अरुणाचल प्रदेश'),
('AR43','12','Personnel Department, Arunachal Pradesh','कर्मचारी विभाग, अरुणाचल प्रदेश'),
('AR4','12','Planning Department, Arunachal Pradesh','योजना विभाग, अरुणाचल प्रदेश'),
('AR25','12','Political and Cabinet Affairs Department, Arunachal Pradesh','राजकीय आणि मंत्रिमंडळ विषयक विभाग, अरुणाचल प्रदेश'),
('AR26','12','Power Department, Arunachal Pradesh','विद्युत विभाग, अरुणाचल प्रदेश'),
('AR27','12','Public Health Engineering Department, Arunachal Pradesh','सार्वजनिक आरोग्य अभियांत्रिकी विभाग, अरुणाचल प्रदेश'),
('AR28','12','Public Works Department, Arunachal Pradesh','सार्वजनिक बांधकाम विभाग, अरुणाचल प्रदेश'),
('AR42','12','Revenue and Excise Department, Arunachal Pradesh','महसूल आणि उत्पादन शुल्क विभाग, अरुणाचल प्रदेश'),
('AR30','12','Rural Development and Panchayati Raj Department, Arunachal Pradesh','ग्रामीण विकास आणि पंचायत राज विभाग, अरुणाचल प्रदेश'),
('AR31','12','Rural Works Department, Arunachal Pradesh','ग्रामीण कामे विभाग, अरुणाचल प्रदेश'),
('AR33','12','Science & Technology Department, Arunachal Pradesh','विज्ञान आणि तंत्रज्ञान विभाग, अरुणाचल प्रदेश'),
('AR61','12','Social Justice and Empowerment and Tribal Affairs Department, Arunachal Pradesh','सामाजिक न्याय आणि सक्षमीकरण व आदिवासी व्यवहार विभाग, अरुणाचल प्रदेश'),
('AR59','12','Tax & Excise Department, Arunachal Pradesh','कर आणि उत्पादन शुल्क विभाग, अरुणाचल प्रदेश'),
('AR34','12','Textile and Handicrafts Department, Arunachal Pradesh','कापड आणि हस्तकला विभाग, अरुणाचल प्रदेश'),
('AR35','12','Tourism Department, Arunachal Pradesh','पर्यटन विभाग, अरुणाचल प्रदेश'),
('AR36','12','Trade and Commerce Department, Arunachal Pradesh','व्यापार आणि वाणिज्य विभाग, अरुणाचल प्रदेश'),
('AR37','12','Transport and Civil Aviation Department, Arunachal Pradesh','वाहतूक आणि नागरी उड्डाण विभाग, अरुणाचल प्रदेश'),
('AR38','12','Urban Development & Housing Department, Arunachal Pradesh','नगरविकास आणि गृहनिर्माण विभाग, अरुणाचल प्रदेश'),
('AR60','12','Women and Child Development Department, Arunachal Pradesh','महिला आणि बालविकास विभाग, अरुणाचल प्रदेश'),
('AR39','12','Youth Affairs and Sports Department, Arunachal Pradesh','युवक व्यवहार आणि क्रीडा विभाग, अरुणाचल प्रदेश'),
('AP20','28','Agriculture and Co-operation Department, Andhra Pradesh','कृषी आणि सहकार विभाग, आंध्र प्रदेश'),
('AP67','28','Animal husbandry and Fisheries Department, Andhra Pradesh','पशुसंवर्धन आणि मत्स्य विभाग, आंध्र प्रदेश'),
('AP77','28','APTWREIS (Gurukulam), Andhra Pradesh','एपीटीडब्ल्यूआरईआयएस (गुरुकुलम), आंध्र प्रदेश'),
('AP23','28','Backward Classes Welfare Department, Andhra Pradesh','मागासवर्गीय कल्याण विभाग, आंध्र प्रदेश'),
('AP76','28','Commercial Taxes Department, Andhra Pradesh','वाणिज्य कर विभाग, आंध्र प्रदेश'),
('AP24','28','Consumer Affairs, Food and Civil Supplies Department, Andhra Pradesh','ग्राहक व्यवहार, अन्न आणि नागरी पुरवठा विभाग, आंध्र प्रदेश'),
('AP19','28','Energy Department, Andhra Pradesh','ऊर्जा विभाग, आंध्र प्रदेश'),
('AP25','28','Environment, Forests, Science and Technology Department, Andhra Pradesh','पर्यावरण, वन, विज्ञान आणि तंत्रज्ञान विभाग, आंध्र प्रदेश'),
('AP26','28','Finance Department, Andhra Pradesh','वित्त विभाग, आंध्र प्रदेश'),
('AP27','28','General Administration Department, Andhra Pradesh','सामान्य प्रशासन विभाग, आंध्र प्रदेश'),
('AP28','28','Health, Medical and Family Welfare Department, Andhra Pradesh','आरोग्य, वैद्यकीय आणि कुटुंब कल्याण विभाग, आंध्र प्रदेश'),
('AP3','28','Higher Education Department, Andhra Pradesh','उच्च शिक्षण विभाग, आंध्र प्रदेश'),
('AP29','28','Home Department, Andhra Pradesh','गृह विभाग, आंध्र प्रदेश'),
('AP30','28','Housing Department, Andhra Pradesh','गृहनिर्माण विभाग, आंध्र प्रदेश'),
('AP31','28','Industries and Commerce Department, Andhra Pradesh','उद्योग आणि वाणिज्य विभाग, आंध्र प्रदेश'),
('AP12','28','Information Technology and Communications Department, Andhra Pradesh','माहिती तंत्रज्ञान आणि संपर्क विभाग, आंध्र प्रदेश'),
('AP32','28','Infrastructure and Investment Department, Andhra Pradesh','पायाभूत सुविधा आणि गुंतवणूक विभाग, आंध्र प्रदेश'),
('AP33','28','Irrigation and Command Area Development Department, Andhra Pradesh','सिंचन आणि आदेश क्षेत्र विकास विभाग, आंध्र प्रदेश'),
('AP34','28','Labour, Employment Training and Factories Department, Andhra Pradesh','कामगार, रोजगार प्रशिक्षण आणि कारखाना विभाग, आंध्र प्रदेश'),
('AP35','28','Law Department, Andhra Pradesh','कायदा विभाग, आंध्र प्रदेश'),
('AP10','28','Minorities Welfare Department, Andhra Pradesh','अल्पसंख्याक कल्याण विभाग, आंध्र प्रदेश'),
('AP18','28','Municipal Administration and Urban Development Department, Andhra Pradesh','महानगरपालिका प्रशासन आणि नगरविकास विभाग, आंध्र प्रदेश'),
('AP6','28','Panchayat Raj & Rural Development Department, Andhra Pradesh','पंचायत राज आणि ग्रामीण विकास विभाग, आंध्र प्रदेश'),
('AP37','28','Planning Department, Andhra Pradesh','योजना विभाग, आंध्र प्रदेश'),
('AP38','28','Public Enterprises Department, Andhra Pradesh','सार्वजनिक उद्योग विभाग, आंध्र प्रदेश'),
('AP39','28','Rain Shadow Areas Development Department, Andhra Pradesh','रेन शॅडो क्षेत्र विकास विभाग, आंध्र प्रदेश'),
('AP9','28','Revenue Department, Andhra Pradesh','महसूल विभाग, आंध्र प्रदेश'),
('AP74','28','School Education Department, Andhra Pradesh','शालेय शिक्षण विभाग, आंध्र प्रदेश'),
('AP75','28','Sericulture Department, Andhra Pradesh','रेशम उद्योग विभाग, आंध्र प्रदेश'),
('AP14','28','Social Welfare Department, Andhra Pradesh','सामाजिक कल्याण विभाग, आंध्र प्रदेश'),
('AP8','28','Transport, Roads and Buildings Department, Andhra Pradesh','वाहतूक, रस्ते आणि इमारत विभाग, आंध्र प्रदेश'),
('AP41','28','Women Development, Child Welfare and Disabled Welfare Department, Andhra Pradesh','महिला विकास, बाल कल्याण आणि अपंग कल्याण विभाग, आंध्र प्रदेश'),
('AP42','28','Youth Advancement, Tourism and Culture Department, Andhra Pradesh','युवा प्रगती, पर्यटन आणि संस्कृती विभाग, आंध्र प्रदेश'),
('AS2','18','Administrative Reforms and Training Department, Assam','प्रशासकीय सुधारणा आणि प्रशिक्षण विभाग, आसाम'),
('AS3','18','Agriculture Department, Assam','कृषी विभाग, आसाम'),
('AS4','18','Animal Husbandry and Veterinary Department, Assam','पशुसंवर्धन आणि पशुवैद्यकीय विभाग, आसाम'),
('AS47','18','Assam Accord Department, Assam','आसाम करार विभाग, आसाम'),
('AS46','18','Border Areas Department, Assam','सीमा क्षेत्र विभाग, आसाम'),
('AS5','18','Co-operation Department, Assam','सहकार विभाग, आसाम'),
('AS6','18','Cultural Affairs Department, Assam','सांस्कृतिक कार्य विभाग, आसाम'),
('AS7','18','Education (Elementary & Secondary) Department, Assam','शिक्षण (प्राथमिक व माध्यमिक) विभाग, आसाम'),
('AS72','18','Education (Higher) Department, Assam','उच्च शिक्षण विभाग, आसाम'),
('AS49','18','Election Department, Assam','निवडणूक विभाग, आसाम'),
('AS54','18','Environment and Forest Department, Assam','पर्यावरण आणि वन विभाग, आसाम'),
('AS53','18','Excise Department, Assam','आबकारी विभाग, आसाम'),
('AS8','18','Finance Department, Assam','वित्त विभाग, आसाम'),
('AS10','18','Fisheries Department, Assam','मत्स्य विभाग, आसाम'),
('AS25','18','Food and Civil Supplies Department, Assam','अन्न आणि नागरी पुरवठा विभाग, आसाम'),
('AS20','18','General Administration Department, Assam','सामान्य प्रशासन विभाग, आसाम'),
('AS21','18','Guwahati Development Department, Assam','गुवाहाटी विकास विभाग, आसाम'),
('AS51','18','Handloom, Textile and Sericulture Department, Assam','हॅंडलूम, वस्त्र आणि रेशीम उद्योग विभाग, आसाम'),
('AS29','18','Health and Family Welfare Department, Assam','आरोग्य आणि कुटुंब कल्याण विभाग, आसाम'),
('AS48','18','Hill Areas Department, Assam','डोंगरी भाग विभाग, आसाम'),
('AS9','18','Home Department, Assam','गृह विभाग, आसाम'),
('AS19','18','Horticulture and Food Processing Department, Assam','फळबागायती आणि अन्न प्रक्रिया विभाग, आसाम'),
('AS16','18','Industries and Commerce Department, Assam','उद्योग आणि वाणिज्य विभाग, आसाम'),
('AS44','18','Information and Public Relations Department, Assam','माहिती व जनसंपर्क विभाग, आसाम'),
('AS18','18','Information Technology Department, Assam','माहिती तंत्रज्ञान विभाग, आसाम'),
('AS26','18','Irrigation Department, Assam','सिंचन विभाग, आसाम'),
('AS52','18','Judicial Department, Assam','न्याय विभाग, आसाम'),
('AS24','18','Labour and Employment Department, Assam','कामगार आणि रोजगार विभाग, आसाम'),
('AS43','18','Legislative Department, Assam','विधीमंडळ विभाग, आसाम'),
('AS35','18','Minority Welfare and Development (Char Areas) Department, Assam','अल्पसंख्याक कल्याण आणि विकास (चार क्षेत्र) विभाग, आसाम'),
('AS11','18','Panchayat and Rural Development Department, Assam','पंचायत आणि ग्रामीण विकास विभाग, आसाम'),
('AS39','18','Parliamentary Affairs Department, Assam','संसदीय कार्य विभाग, आसाम'),
('AS37','18','Passport Department, Assam','पासपोर्ट विभाग, आसाम'),
('AS17','18','Pension and Public Grievances Department, Assam','पेन्शन आणि सार्वजनिक तक्रार विभाग, आसाम'),
('AS12','18','Personnel Department, Assam','कार्मिक विभाग, आसाम'),
('AS1','18','Planning and Development Department, Assam','योजना आणि विकास विभाग, आसाम'),
('AS22','18','Political Department, Assam','राजकीय विभाग, आसाम'),
('AS27','18','Power (Electricity), Mines and Minerals Department, Assam','वीज, खाण आणि खनिज विभाग, आसाम'),
('AS50','18','Printing and Stationary Department, Assam','मुद्रण व लेखनसामग्री विभाग, आसाम'),
('AS40','18','Public Enterprises Department, Assam','सार्वजनिक उद्योग विभाग, आसाम'),
('AS23','18','Public Health Engineering Department, Assam','सार्वजनिक आरोग्य अभियांत्रिकी विभाग, आसाम'),
('AS13','18','Public Works Department, Assam','सार्वजनिक बांधकाम विभाग, आसाम'),
('AS15','18','Revenue & Disaster Management Department, Assam','महसूल आणि आपत्ती व्यवस्थापन विभाग, आसाम'),
('AS41','18','Science and Technology Department, Assam','विज्ञान आणि तंत्रज्ञान विभाग, आसाम'),
('AS45','18','Secretariat Administration Department, Assam','सचिवालय प्रशासन विभाग, आसाम'),
('AS14','18','Social Welfare Department, Assam','सामाजिक कल्याण विभाग, आसाम'),
('AS42','18','Soil Conservation Department, Assam','मृदा संवर्धन विभाग, आसाम'),
('AS30','18','Sports and Youth Welfare Department, Assam','क्रीडा आणि युवक कल्याण विभाग, आसाम'),
('AS38','18','Tea Tribes Welfare Department, Assam','चहा जमाती कल्याण विभाग, आसाम'),
('AS71','18','Tourism Department, Assam','पर्यटन विभाग, आसाम'),
('AS73','18','Transport Department, Assam','वाहतूक विभाग, आसाम'),
('AS33','18','Urban Development Department, Assam','नगर विकास विभाग, आसाम'),
('AS36','18','Water Resources Department, Assam','जल संसाधन विभाग, आसाम'),
('AS28','18','Welfare of Plain Tribes and Backward Classes Department, Assam','सपाट जमाती आणि मागास वर्ग कल्याण विभाग, आसाम'),
('BR12','10','Agriculture Department, Bihar','कृषी विभाग, बिहार'),
('BR13','10','Animal & Fish Resources Department, Bihar','प्राणी आणि मासे संसाधन विभाग, बिहार'),
('BR46','10','BC and MBC Welfare Department, Bihar','इतर मागास व अतिमागास कल्याण विभाग, बिहार'),
('BR17','10','Building Construction Department, Bihar','भवन बांधकाम विभाग, बिहार'),
('BR18','10','Co-operative Department, Bihar','सहकारी विभाग, बिहार'),
('BR6','10','Commercial Taxes Department, Bihar','व्यावसायिक कर विभाग, बिहार'),
('BR50','10','Department of Social Welfare (DoSW), Government of Bihar','सामाजिक कल्याण विभाग, बिहार सरकार'),
('BR19','10','Disaster Management Department, Bihar','आपत्ती व्यवस्थापन विभाग, बिहार'),
('BR52','10','Education Department, Bihar','शिक्षण विभाग, बिहार'),
('BR20','10','Energy Department, Bihar','ऊर्जा विभाग, बिहार'),
('BR21','10','Environment & Forest Department, Bihar','पर्यावरण व वन विभाग, बिहार'),
('BR3','10','Finance Department, Bihar','वित्त विभाग, बिहार'),
('BR22','10','Food and Consumer Protection Department, Bihar','अन्न व ग्राहक संरक्षण विभाग, बिहार'),
('BR23','10','General Administration Department, Bihar','सामान्य प्रशासन विभाग, बिहार'),
('BR24','10','Health & Family Welfare Department, Bihar','आरोग्य व कुटुंब कल्याण विभाग, बिहार'),
('BR25','10','Home Department, Bihar','गृह विभाग, बिहार'),
('BR26','10','Human Resource Development Department, Bihar','मानव संसाधन विकास विभाग, बिहार'),
('BR27','10','Industry Department, Bihar','उद्योग विभाग, बिहार'),
('BR28','10','Information & Public Relations Department, Bihar','माहिती व जनसंपर्क विभाग, बिहार'),
('BR47','10','Information Technology Department, Bihar','माहिती तंत्रज्ञान विभाग, बिहार'),
('BR29','10','Labour Resources (Employment and Training) Department, Bihar','कामगार संसाधन (रोजगार व प्रशिक्षण) विभाग, बिहार'),
('BR30','10','Law Department, Bihar','कायदा विभाग, बिहार'),
('BR48','10','Mines & Geology Department, Bihar','खनिज व भूगर्भशास्त्र विभाग, बिहार'),
('BR51','10','Minor Water Resources Department, Bihar','लघु जलसंपदा विभाग, बिहार'),
('BR15','10','Minority Welfare Department, Bihar','अल्पसंख्याक कल्याण विभाग, बिहार'),
('BR31','10','Panchayat Raj Department, Bihar','पंचायत राज विभाग, बिहार'),
('BR45','10','Parliamentary Affairs Department, Bihar','संसदीय कार्य विभाग, बिहार'),
('BR33','10','Planning & Development Department, Bihar','योजना व विकास विभाग, बिहार'),
('BR32','10','Public Health Engineering Department, Bihar','सार्वजनिक आरोग्य अभियांत्रिकी विभाग, बिहार'),
('BR34','10','Registration, Excise & Prohibition Department, Bihar','नोंदणी, उत्पादन शुल्क व प्रतिबंध विभाग, बिहार'),
('BR14','10','Revenue & Land Reforms Department, Bihar','महसूल व भूमी सुधार विभाग, बिहार'),
('BR16','10','Road Construction Department, Bihar','रस्ता बांधकाम विभाग, बिहार'),
('BR35','10','Rural Development Department, Bihar','ग्रामीण विकास विभाग, बिहार'),
('BR36','10','Rural Works Department, Bihar','ग्रामीण कार्य विभाग, बिहार'),
('BR49','10','SC & ST Welfare Department, Bihar','अनुसूचित जाती व अनुसूचित जमाती कल्याण विभाग, बिहार'),
('BR37','10','Science & Technology Department, Bihar','विज्ञान व तंत्रज्ञान विभाग, बिहार'),
('BR43','10','Social Welfare Department, Bihar','सामाजिक कल्याण विभाग, बिहार'),
('BR38','10','Sugarcane Development Department, Bihar','ऊस विकास विभाग, बिहार'),
('BR39','10','Tourism Department, Bihar','पर्यटन विभाग, बिहार'),
('BR8','10','Transport Department, Bihar','वाहतूक विभाग, बिहार'),
('BR40','10','Urban Development & Housing Department, Bihar','नगर विकास व गृहनिर्माण विभाग, बिहार'),
('BR41','10','Vigilance Department, Bihar','सतर्कता विभाग, बिहार'),
('BR42','10','Water Resources (Irrigation) Department, Bihar','जलसंपदा (सिंचन) विभाग, बिहार'),
('BR44','10','Youth, Art & Culture Department, Bihar','युवा, कला व संस्कृती विभाग, बिहार')


--------Ministry table--------------------------------------------------------------

CREATE TABLE m_ministry (
    ministry_code VARCHAR(10) NOT NULL PRIMARY KEY,
    ministry_name VARCHAR(255) NOT NULL,
    ministry_name_ll VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    insert_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    insert_ip VARCHAR(50) NOT NULL DEFAULT 'NA',
    insert_by VARCHAR(100) NOT NULL DEFAULT 'NA',
    updated_date TIMESTAMP DEFAULT NULL,
    update_ip VARCHAR(50) DEFAULT NULL,
    update_by VARCHAR(100) DEFAULT NULL
);


INSERT INTO m_ministry (ministry_code,ministry_name,ministry_name_ll)
VALUES
('53','Cabinet Secretariat','कॅबिनेट सचिवालय'),
('1543','Central Information Commission (CIC)','केंद्रीय माहिती आयोग'),
('1520','Comptroller And Auditor General of India(CAG)','भारताचे नियंत्रक आणि महालेखापरीक्षक'),
('54','Department of Atomic Energy','अणुऊर्जा विभाग'),
('55','Department of Space','अंतराळ विभाग'),
('1540','Election Commission of India','भारत निवडणूक आयोग'),
('10009','Lok Sabha','लोकसभा'),
('1','Ministry of Agriculture','कृषी मंत्रालय'),
('10003','Ministry of Ayurveda, Yoga and Naturopathy, Unani, Siddha and Homoeopathy','आयुर्वेद, योग आणि नैसर्गिक चिकित्सा, युनानी, सिद्ध आणि होमिओपॅथी मंत्रालय'),
('3','Ministry of Chemicals and Fertilizers','रसायने आणि खते मंत्रालय'),
('4','Ministry of Civil Aviation','नागरी विमान वाहतूक मंत्रालय'),
('5','Ministry of Coal','कोळसा मंत्रालय'),
('6','Ministry of Commerce and Industry','वाणिज्य आणि उद्योग मंत्रालय'),
('7','Ministry of Communications','संचार मंत्रालय'),
('8','Ministry of Consumer Affairs, Food and Public Distribution','ग्राहक व्यवहार, अन्न आणि सार्वजनिक वितरण मंत्रालय'),
('10014','Ministry of Cooperation','सहकार मंत्रालय'),
('9','Ministry of Corporate Affairs','कॉर्पोरेट व्यवहार मंत्रालय'),
('10','Ministry of Culture','संस्कृती मंत्रालय'),
('11','Ministry of Defence','संरक्षण मंत्रालय'),
('56','Ministry of Development of North Eastern Region','ईशान्य प्रदेश विकास मंत्रालय'),
('12','Ministry of Earth Sciences','पृथ्वी विज्ञान मंत्रालय'),
('21','Ministry of Education','शिक्षण मंत्रालय'),
('248','Ministry of Electronics and Information Technology (MeitY)','इलेक्ट्रॉनिक्स आणि माहिती तंत्रज्ञान मंत्रालय'),
('10004','Ministry of Environment, Forest and Climate Change','पर्यावरण, वन आणि हवामान बदल मंत्रालय'),
('14','Ministry of External Affairs','परराष्ट्र मंत्रालय'),
('15','Ministry of Finance','वित्त मंत्रालय'),
('5517','Ministry of Fisheries, Animal Husbandry and Dairying','मत्स्य, पशुसंवर्धन आणि दुग्धव्यवसाय मंत्रालय'),
('16','Ministry of Food Processing Industries','अन्न प्रक्रिया उद्योग मंत्रालय'),
('17','Ministry of Health and Family Welfare','आरोग्य आणि कुटुंब कल्याण मंत्रालय'),
('18','Ministry of Heavy Industries and Public Enterprises','जड उद्योग आणि सार्वजनिक उपक्रम मंत्रालय'),
('19','Ministry of Home Affairs','गृह मंत्रालय'),
('20','Ministry of Housing and Urban Affairs','गृहनिर्माण आणि शहरी व्यवहार मंत्रालय'),
('22','Ministry of Information and Broadcasting','माहिती आणि प्रसारण मंत्रालय'),
('49','Ministry of Jal Shakti','जल शक्ती मंत्रालय'),
('23','Ministry of Labour and Employment','कामगार आणि रोजगार मंत्रालय'),
('24','Ministry of Law and Justice','कायदा आणि न्याय मंत्रालय'),
('41','Ministry of Micro, Small and Medium Enterprises','सूक्ष्म, लघु आणि मध्यम उद्योग मंत्रालय'),
('25','Ministry of Mines','खाण मंत्रालय'),
('26','Ministry of Minority Affairs','अल्पसंख्याक व्यवहार मंत्रालय'),
('27','Ministry of New and Renewable Energy','नवीन आणि नवीकरणीय ऊर्जा मंत्रालय'),
('29','Ministry of Overseas Indian Affairs','परदेशी भारतीय व्यवहार मंत्रालय'),
('30','Ministry of Panchayati Raj','पंचायती राज मंत्रालय'),
('31','Ministry of Parliamentary Affairs','संसदीय कार्य मंत्रालय'),
('32','Ministry of Personnel, Public Grievances and Pensions','कार्मिक, सार्वजनिक तक्रारी आणि पेन्शन मंत्रालय'),
('33','Ministry of Petroleum and Natural Gas','पेट्रोलियम आणि नैसर्गिक वायू मंत्रालय'),
('34','Ministry of Planning','योजना मंत्रालय'),
('1237','Ministry of Ports, Shipping and Waterways','बंदर, नौकानयन आणि जलमार्ग मंत्रालय'),
('35','Ministry of Power','वीज मंत्रालय'),
('36','Ministry of Railways','रेल्वे मंत्रालय'),
('40','Ministry of Road Transport and Highways','सड़क वाहतूक आणि महामार्ग मंत्रालय'),
('38','Ministry of Rural Development','ग्रामीण विकास मंत्रालय'),
('39','Ministry of Science and Technology','विज्ञान आणि तंत्रज्ञान मंत्रालय'),
('10001','Ministry of Skill Development and Entrepreneurship','कौशल्य विकास आणि उद्योजकता मंत्रालय'),
('42','Ministry of Social Justice and Empowerment','सामाजिक न्याय आणि अधिकारिता मंत्रालय'),
('43','Ministry of Statistics and Programme Implementation','सांख्यिकी आणि कार्यक्रम अंमलबजावणी मंत्रालय'),
('44','Ministry of Steel','स्टील मंत्रालय'),
('45','Ministry of Textiles','कापड मंत्रालय'),
('46','Ministry of Tourism','पर्यटन मंत्रालय'),
('47','Ministry of Tribal Affairs','आदिवासी कामकाज मंत्रालय'),
('50','Ministry of Women and Child Development','महिला आणि बाल विकास मंत्रालय'),
('51','Ministry of Youth Affairs and Sports','युवा व्यवहार आणि क्रीडा मंत्रालय'),
('10013','National Company Law Appellate Tribunal (NCLAT)','राष्ट्रीय कंपनी कायदा अपील न्यायाधिकरण'),
('10012','National Company Law Tribunal (NCLT)','राष्ट्रीय कंपनी कायदा न्यायाधिकरण'),
('1534','National Human Rights Commissions(NHRC)','राष्ट्रीय मानवाधिकार आयोग'),
('1532','NITI Aayog (National Institution for Transforming India)','नीती आयोग'),
('1544','Office of the Principal Scientific Adviser','मुख्य वैज्ञानिक सल्लागार कार्यालय'),
('11000','Others','इतर'),
('10006','Presidents Secretariat','राष्ट्रपती सचिवालय'),
('60','Prime Minister''s Office','पंतप्रधान कार्यालय'),
('10010','Rajya Sabha','राज्यसभा'),
('10011','Supreme Court of India','भारताचा सर्वोच्च न्यायालय'),
('1537','Union Public Service Commission (UPSC)','संघ लोकसेवा आयोग'),
('1643','Vice President of India','भारताचे उपराष्ट्रपती')

select * from m_department
select * from m_ministry

UPDATE m_department
SET dept_name = 'Agriculture & Farmers Department,Maharashtra'   
WHERE dept_code = 'MH7';
